// Generated by scripts/generate-jlpt-vocabulary.mjs and supplemented from the user-provided TRY N1 PDF.
// Vocabulary entries are stored in generatedVocabulary.json to keep TypeScript fast.
import type { StudyWord } from "./studyContent";
import rawVocabulary from "./generatedVocabulary.json";

export const generatedVocabularySource = {
  name: "JLPT Vocabulary API + TRY N1 PDF",
  url: "https://jlpt-vocab-api.vercel.app/",
  generatedAt: "2026-08-16T06:48:04.625Z",
  count: 4276,
  tryN1Count: 1398
};

export const generatedVocabulary = rawVocabulary as StudyWord[];
