// Generated by scripts/generate-jlpt-vocabulary.mjs.
// Source: https://jlpt-vocab-api.vercel.app/
// Vocabulary entries are stored in generatedVocabulary.json to keep TypeScript fast.
import type { StudyWord } from "./studyContent";
import rawVocabulary from "./generatedVocabulary.json";

export const generatedVocabularySource = {
  name: "JLPT Vocabulary API",
  url: "https://jlpt-vocab-api.vercel.app/",
  generatedAt: "2026-08-05T15:15:43.677Z",
  count: 3100
};

export const generatedVocabulary = rawVocabulary as StudyWord[];
